import {
  ContextProvider,
  ReservationProvider,
} from "./_components/ReservationContext.js";
import Header from "./_components/Header";

import "@/app/_styles/globals.css";
export const metadata = {
  // title: "The Wild Oasis",
  title: {
    template: "%s / The Wild Oasis",
    default: "Welcome / The Wild Oasis",

    description: "Generated by Next.js",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-950 text-primary-100 mx-2 min-h-screen flex flex-col">
        <header>
          <Header />
        </header>

        <div className="flex-1 py-8 px-12">
          <main className="max-w-7xl mx-auto ">
            <ReservationProvider>{children}</ReservationProvider>
          </main>
        </div>
        <footer className="bg-primary-900 text-primary-300 py-4 text-center"></footer>
      </body>
    </html>
  );
}
